# Generated by Django 4.1.13 on 2024-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(default=None, max_length=200)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('grade', models.IntegerField(default=1, max_length=1)),
                ('major', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
