# Generated by Django 4.1.13 on 2024-04-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app2", "0003_student_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="student_data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "my_collection",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
